# Generated by Selenium IDE
from selenium import webdriver
import time



class TestYandex():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def test_1(self):
        self.open_site()
        self.login()


    def teardown_method(self, method):
        self.driver.quit()


    def open_site(self):
        self.driver.get("https://yandex.ru")

    def login(self):
        self.driver.find_element_by_link_text('Войти в почту').click()
        self.driver.find_element_by_name('login').send_keys('poterok')
        self.driver.find_element_by_class_name('passp-flex-wrapper')
        time.sleep(1)

        time.sleep(1)
        # Войти
        self.driver.find_element_by_class_name('button2_type_submit').click()
        time.sleep(1)
        self.driver.find_element_by_id('passp-field-passwd').send_keys('Mnata1991')
        self.driver.find_element_by_class_name('button2_type_submit').click()

        time.sleep(100)
