# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
import selenium.webdriver.common.action_chains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestname():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testname(self):
    self.driver.get("https://id.rambler.ru/login-20/login?back=https%3A%2F%2Fwww.rambler.ru&rname=head&type=self")
    time.sleep(1)

    self.driver.find_element_by_id("login").click()
    self.driver.find_element_by_id("login").send_keys("potr4ik")
    self.driver.find_element_by_id("password").clear()
    self.driver.find_element_by_id("password").send_keys("2012Potr")
    time.sleep(1)
    self.driver.find_element_by_css_selector('span.rui-Button-content').click()
    time.sleep(1)
    self.driver.find_element_by_css_selector('span.rui__1vTeO').click()
    time.sleep(1)

    # time.sleep(2)
    self.driver.find_element_by_css_selector('a.rui__iDgq5').click()
    time.sleep(10)
    # self.driver.find_element_by_css_selector('a.rui__iDgq5')

  
