# coding=utf-8
# Generated by Selenium IDE



from Barancev_Test_QA.group import Group
from Barancev_Test_QA.aplication import Aplication
import pytest


@pytest.fixture()
def app(request):
    fixture = Aplication()
    request.addfinilazer(fixture.destroy_app())
    return  fixture


class TestYandex():
    def setup_method(app):
        app = Aplication

    def test_1_delete_group(app, group_name = "Новая группа"):
        app.open_site()
        app.login(Group(username='poterok', password='Mnata1991'))
        app.go_to_contacts()
        app.go_to_new_group(group_name)
        app.go_to_settings_group()
        app.choose_group_for_delete()
        app.delete_group()
        # app.open_site()
        self.app.logout()


    def test_2_create_new_group(app, group_name = "Новая группа"):
        app.open_site()
        app.login(Group(username='poterok', password= 'Mnata1991'))
        app.go_to_contacts()
        app.create_new_group(group_name)
        # app.open_site()
        app.logout()

    def test_3_login_logout(self):
        app.open_site()
        app.login(Group(username='poterok', password='Mnata1991'))
        app.logout()
