# # coding=utf-8
# # Generated by Selenium IDE
# from model.auth import Auth
#
#
#
# def test_3_login_logout(app):
#     app.open_site()
#     app.session.login(Auth(username='poterok', password='Mnata1991'))
#     app.session.logout()