# coding=utf-8
# Generated by Selenium IDE
from model.group_auth import Group


def test_2_create_new_group(app):
    app.open_site()
    app.session.login(Group(username='poterok', password='Mnata1991'))
    app.group.go_to_contacts()
    app.group.create_new_group(group_name="Новая группа")
    app.session.logout()


