# coding=utf-8
# Generated by Selenium IDE
from model.group_auth import Group
from fixture.application import Application
import pytest


@pytest.fixture
def app(request):
    fixture = Application()
    request.addfinalizer(fixture.destroy)
    return fixture


def test_1_delete_group( app):
    app.open_site()
    app.session.login(Group(username='poterok', password='Mnata1991'))
    app.group.go_to_contacts()
    app.group.go_to_new_group()
    app.group.go_to_settings_group()
    app.group.choose_group_for_delete()
    app.group.delete_group()
    app.session.logout()