# coding=utf-8
# Generated by Selenium IDE
from model.auth import Auth



def test_1_delete_group(app):
    app.open_site()
    app.session.login(Auth(username='poterok', password='Mnata1991'))
    app.group.go_to_contacts()
    app.group.go_to_new_group()
    app.group.go_to_settings_group()
    app.group.choose_group_for_delete()
    app.group.delete_group()
    app.session.logout()