# coding=utf-8
# Generated by Selenium IDE
from model.group_auth import Group






def test_3_login_logout(app):
    app.open_site()
    app.session.login(Group(username='poterok', password='Mnata1991'))
    app.session.logout()